subinclude("//build_defs:rust", "//build_defs:rust_repo")

# Test rust_repo with cfg-if (a simple crate with no deps)
rust_repo(
    lock = "",
    name = "cfg_if",
    crate = "cfg-if",
    version = "1.0.0",
)
