# Self-reference to load rust-rules as a plugin (like go-rules does)
plugin_repo(
    name = "rust",
    owner = "becomeliminal",
    plugin = "rust-rules",
    revision = "master",
)

plugin_repo(
    name = "shell",
    revision = "v0.2.0",
)

plugin_repo(
    name = "proto",
    revision = "v0.4.0",
)

plugin_repo(
    name = "go-proto",
    revision = "v0.3.0",
)

plugin_repo(
    name = "python",
    revision = "v1.6.0",
)

plugin_repo(
    name = "cc",
    revision = "v0.7.1",
)
