# Self-reference to load rust-rules as a plugin (like go-rules does)
plugin_repo(
    name = "rust",
    owner = "becomeliminal",
    plugin = "rust-rules",
    revision = "master",
)

plugin_repo(
    name = "shell",
    revision = "v0.2.0",
)

plugin_repo(
    name = "cc",
    revision = "v0.7.1",
)

plugin_repo(
    name = "e2e",
    plugin = "plugin-integration-testing",
    revision = "v1.0.3",
)
