filegroup(
    name = "rust",
    srcs = [
        "rust_toolchain.build_defs",
        "rust.build_defs",
        "rust_crate.build_defs",
        "rust_deps_check.build_defs",
    ],
    visibility = ["PUBLIC"],
)
