#include <stdio.h>
// Generated by rust_cbindgen from rust_ffi_lib.rs. Declaring ffi_add by hand
// here is what this is replacing: nothing checked it against the Rust.
#include "ffi_header.h"
int main(void) {
    printf("rust says %d\n", ffi_add(40, 2));
    return 0;
}
